config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :articles do
    resources :comments
  end

  get 'signup', to: 'users#new' 
  resources :users 

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy' 


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :user_id, presence: true
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :articles

    validates :password, presence: true, confirmation: true, length: { minimum: 8 }
    validate :password_complexity

    private
    def password_complexity
        if password.present? && !password.match(/(?=.*[A-Z])(?=.*\d)/)
            errors.add :password, 'Your password must include at least one uppercase letter and one digit'
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

   def require_user
    redirect_to '/login' unless current_user
   end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  ##before_action :require_user, only: [:index, :show]
  before_action :require_user, only: [:new, :create]
  before_action :require_owner, only: [:edit, :update, :destroy]

  def index
    @articles = Article.order(:created_at => :desc)
    @pagy, @articles = pagy(Article.all, items: 3)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.create(article_params)

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  def require_owner
    @article = Article.find(params[:id])
    unless @article.user == current_user
      redirect_to root_path, alert: "You can only edit or delete your own articles."
    end
  end
  
  private
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new; end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/', allow_other_host: true
    else
      redirect_to '/login', allow_other_host: true
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

end

app/helpers/articles_helper.rb
module ArticlesHelper
  include Pagy::Frontend
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<nav class="navbar has-background-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item has-text-white" href="<%= root_path %>">
      Home
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if current_user %>
            <%= button_to "Log out", logout_path, method: "delete", class: 'button is-primary' %>
          <% else %>
            <%= link_to "Login", 'login', class: 'button is-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

<div class="container is-max-widescreen">
  <section class="section is-medium">
    <%= form_with model: article do |form| %>
      <div class="card">
        <div class="card-content">
          <div class="content">
            <h1 class="title has-text-centered has-text-white">New Article</h1>
            <div class="field">
              <label class="label has-text-white">Title</label>
              <div class="control has-icons-left">
                <%= form.text_field :title, class:"input" %>
                <% article.errors.full_messages_for(:title).each do |message| %>
                  <div><%= message %></div>
                <% end %>
                <span class="icon is-small is-left">
                  <i class="fas fa-heading"></i>
                </span>
              </div>
            </div>
            <br>
            <div class="field">
              <label class="label has-text-white">Body</label>
              <div class="control has-icons-left">
                <%= form.text_area :body, class: "textarea" %><br>
                <% article.errors.full_messages_for(:body).each do |message| %>
                  <div><%= message %></div>
                <% end %>
              </div>
            </div>
            <div class="field">
              <%= form.submit "Post", class: "button is-primary" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </section>
</div>

<footer class="footer has-background-dark">
  <div class="content has-text-centered">
    <p class="has-text-white">© <%= Time.now.year %> All rights reserved</p>
  </div>
</footer>

app/views/articles/edit.html.erb
<%= render "form", article: @article %>
<h1>Edit Article</h1>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wesley's Blog</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <script src="https://kit.fontawesome.com/ab398cb506.js" crossorigin="anonymous"></script>
</head>
<body class="has-background-dark has-text-white">
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="<%= root_path %>">
      <h1 class="title">Welcome to Wesley's Blog</h1>
    </a>
  </div>

  <div class="navbar-menu" style="display: flex; justify-content: center; flex-grow: 1;">
    <% if current_user %>
      <p class="navbar-item subtitle">Hello, <%= current_user.first_name %>!</p>
    <% else %>
      <p class="navbar-item subtitle">Hello!</p>
    <% end %>
  </div>

  <div class="navbar-end">
    <div class="navbar-item">
      <div class="buttons">
        <% if current_user %>
          <%= button_to "Log out", logout_path, method: "delete", class: 'button is-primary' %>
        <% else %>
          <%= link_to "Login", 'login', class: 'button is-primary' %>
          <%= link_to "Sign up", 'signup', class: 'button is-secondary' %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

<div class="container mt-5">
  <div class="columns">
    <div class="column is-two-thirds is-offset-2">
      <button class="card js-modal-trigger mb-5" data-target="modal-js-example">
        <div class="card-content has-text-centered">
          <span class="icon is-large">
            <i class="fas fa-plus fa-3x"></i>
          </span>
          <p class="title is-4">Create new post</p>
        </div>
      </button>

      <h1 class="title is-2 has-text-centered">Articles</h1>

      <% @articles.each do |article| %>
        <div class="card mb-4">
          <div class="card-content">
            <p class="title"><%= link_to article.title, article %></p>
            <p class="subtitle"><%= article.body.split("\n").first %></p>
            <p><strong>Author:</strong> <%= article.user.first_name %> <%= article.user.last_name %></p>
            <p><strong>Published:</strong> <%= article.created_at.strftime("%B %d, %Y") %></p>
          </div>
        </div>
      <% end %>

      <%== pagy_nav(@pagy, ) %>
    </div>
  </div>
</div>

<div id="modal-js-example" class="modal">
  <div class="modal-background"></div>

  <div class="modal-content">
    <div class="modal-card">
      <header class="modal-card-head">
        <p class="modal-card-title">Add new post</p>
      </header>
      <section class="modal-card-body">
        <%= form_with model: @article do |form| %>
          <div class="field">
            <label class="label">Title</label>
            <div class="control">
              <%= form.text_field :title, class: "input" %>
            </div>
          </div>

          <div class="field">
            <label class="label">Body</label>
            <div class="control">
              <%= form.text_area :body, class: "textarea" %>
            </div>
          </div>
      </section>
      <footer class="modal-card-foot">
        <div class="buttons">
          <%= form.submit "Post", class: "button is-primary" %>
          <button class="button is-danger" onclick="closeModal()">Cancel</button>
        </div>
      </footer>
      <% end %>
    </div>
    <button class="modal-close is-large" aria-label="close" onclick="closeModal()"></button>
  </div>
</div>

<footer class="footer has-background-dark has-text-centered has-text-white mt-6">
  <div class="content">
    <p>All rights reserved. &copy; <%= Time.now.year %> Wesley's Blog</p>
  </div>
</footer>

<script>
  function closeModal() {
    var modal = document.getElementById('modal-js-example');
    modal.classList.remove('is-active');
  }
</script>

</body>
</html>

app/views/articles/new.html.erb
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<% if current_user == @article.user %>
<ul>
  <li><%= link_to "Edit", edit_article_path(@article), class: 'primary-button' %></li>
  <li><%= link_to "Destroy", article_path(@article), class: 'primary-button', data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>
<% end %>


<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to "Destroy Comment", [comment.article, comment], data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  } %>
</p>

<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
        <%= form.label :commenter %><br>
        <%= form.text_field :commenter %>
    </p>
    <p>
        <%= form.label :body %><br>
        <%= form.text_area :body %>
    </p>

    <%= form.submit %>
<% end %>

<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <% if current_user %>
      <%= form.hidden_field :commenter, value: "#{current_user.first_name} #{current_user.last_name}" %>
      <strong>Comment as <%= "#{current_user.first_name} #{current_user.last_name}" %></strong>
    <% else %>
      <%= form.label :commenter %><br>
      <%= form.text_field :commenter %>
    <% end %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>

  <%= form.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wesley</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://kit.fontawesome.com/ab398cb506.js" crossOrigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>

  <script>
      document.addEventListener('DOMContentLoaded', () => {
          // Functions to open and close a modal
          function openModal($el) {
              $el.classList.add('is-active');
          }

          function closeModal($el) {
              $el.classList.remove('is-active');
          }

          function closeAllModals() {
              (document.querySelectorAll('.modal') || []).forEach(($modal) => {
                  closeModal($modal);
              });
          }

          // Add a click event on buttons to open a specific modal
          (document.querySelectorAll('.js-modal-trigger') || []).forEach(($trigger) => {
              const modal = $trigger.dataset.target;
              const $target = document.getElementById(modal);

              $trigger.addEventListener('click', () => {
                  openModal($target);
              });
          });

          // Add a click event on various child elements to close the parent modal
          (document.querySelectorAll('.modal-background, .modal-close, .modal-card-head .delete, .modal-card-foot .button') || []).forEach(($close) => {
              const $target = $close.closest('.modal');

              $close.addEventListener('click', () => {
                  closeModal($target);
              });
          });

          // Add a keyboard event to close all modals
          document.addEventListener('keydown', (event) => {
              if(event.key === "Escape") {
                  closeAllModals();
              }
          });
      });
  </script>
  </body>
</html>

app/views/users/new.html.erb
<nav class="navbar has-background-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item has-text-white" href="<%= root_path %>">
      Home
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if current_user %>
            <%= button_to "Log out", logout_path, method: "delete", class: 'button is-primary' %>
          <% else %>
            <%= link_to "Login", 'login', class: 'button is-primary' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

<div class="container.is-max-widescreen">

  <section class="section is-medium">
    <div class="card">
      <div class="card-content">
        <div class="content">
          <h1 class="title has-text-centered has-text-white">Sign up</h1>

          <%= form_for(@user) do |f| %>

            <div class="field">
              <label class="label has-text-white">First Name</label>
              <div class="control has-icons-left">
                <%= f.text_field :first_name, :placeholder => "First Name", class: "input" %>
                <span class="icon is-small is-left">
                  <i class="fas fa-user"></i>
                </span>
              </div>
            </div>

            <div class="field">
              <label class="label has-text-white">Last Name</label>
              <div class="control has-icons-left">
                <%= f.text_field :last_name, :placeholder => "Last Name", class: "input" %>
                <span class="icon is-small is-left">
                  <i class="fas fa-user"></i>
                </span>
              </div>
            </div>

            <div class="field">
              <label class="label has-text-white">Email</label>
              <div class="control has-icons-left">
                <%= f.email_field :email, :placeholder => "Email", class: "input" %>
                <span class="icon is-small is-left">
                  <i class="fas fa-envelope"></i>
                </span>
              </div>
            </div>

            <div class="field">
              <label class="label has-text-white">Password</label>
              <div class="control has-icons-left">
                <%= f.password_field :password, :placeholder => "Password", class: "input" %>
                <span class="icon is-small is-left">
                  <i class="fas fa-lock"></i>
                </span>
              </div>
            </div>

            <div class="field">
              <label class="label has-text-white">Confirm Password</label>
              <div class="control has-icons-left">
                <%= f.password_field :password_confirmation, :placeholder => "Confirm Password", class: "input" %>
                <span class="icon is-small is-left">
                  <i class="fas fa-lock"></i>
                </span>
              </div>
            </div>

            <div class="field">
              <%= f.submit "Create an Account", class: "button is-primary" %>
            </div>
          <% end %>

        </div>
      </div>
    </div>
  </section>
</div>
<footer class="footer has-background-dark">
  <div class="content has-text-centered">
    <p class="has-text-white">© <%= Time.now.year %> Todos os direitos reservados</p>
  </div>
</footer>
</div>